#!/bin/bash

# Tear down test environment
cleanup () {
    rc=$?
    cd $user_dir
    echo "Exit status: $rc"
}
trap cleanup EXIT

# Set up test environment
set -eo pipefail  # ensures that script exits at first command that exits with non-zero status
set -u  # ensures that script exits when unset variables are used
set -x  # facilitates debugging by printing out executed commands
user_dir=$PWD

# Remove all generated by the test runs
rm -rf .snakemake/
rm -rf .tmp/
rm -rf logs/
rm -rf results/
rm -rf snakemake_report_*.html
rm -rf wget-log*
