#!/bin/bash

# Tear down test environment
cleanup () {
    rc=$?
    cd $PWD
    echo "Exit status: $rc"
}
trap cleanup EXIT

# Set up test environment
set -eo pipefail  # ensures that script exits at first command that exits with non-zero status
set -u  # ensures that script exits when unset variables are used
set -x  # facilitates debugging by printing out executed commands

# Store repository's root directory
ROOT="$(git rev-parse --show-toplevel)"

# Remove all generated by the test:
rm -rf "$ROOT/.snakemake/"
rm -rf "$ROOT/logs/"
rm -rf "$ROOT/results/"
rm -rf "$ROOT/snakemake_report.html"
