#!/bin/bash

# Tear down test environment
cleanup () {
    rc=$?
    cd $PWD
    echo "Exit status: $rc"
}
trap cleanup EXIT

# Set up test environment
set -eo pipefail  # ensures that script exits at first command that exits with non-zero status
set -u  # ensures that script exits when unset variables are used
set -x  # facilitates debugging by printing out executed commands

# Store repository's root directory
ROOT="$(git rev-parse --show-toplevel)"
TEST="${ROOT}/test"

# Remove all generated by the test:
# Create Rule Graph
rm -rf "$TEST/test_create_rule_graph/.snakemake/"

# Snakemake Format and Lint
rm -rf "$TEST/test_format/.snakemake/"
#
# Workflow Continuous Integration
rm -rf "$TEST/test_integration_workflow/.snakemake/"
rm -rf "$TEST/test_integration_workflow/logs/"
rm -rf "$TEST/test_integration_workflow/results/"
rm -rf "$TEST/test_integration_workflow/snakemake_report.html"
