---
  ##############################################################################
  ### Necessary inputs
  ##############################################################################
  organism: " "
  genome_url: "ftp:// ..... "
  gtf_url: "ftp:// ..... "
  prefix_name: " "
  
  ##############################################################################
  ### Directories
  ##############################################################################
  output_dir: "results"
  scripts_dir: "../scripts"
  local_log: "logs/local"
  cluster_log: "logs/cluster"
...
