default:
  tags:
    - shell

before_script:
  - mamba env create --force -f environment.yml
  - conda activate mir-pipelines
  - echo $CONDA_DEFAULT_ENV
  - snakemake --version

test:
  script:
    - bash test/test_dag.sh
    - bash test/test_rule_graph.sh
    - bash test/test_workflow_local.sh

