image: continuumio/miniconda3:4.7.12

before_script:
  - apt update && apt install -y gcc
  - conda init bash && source ~/.bashrc && echo $CONDA_DEFAULT_ENV
  - conda env create -f environment.yml
  - conda activate mir_pipelines && echo $CONDA_DEFAULT_ENV
  - cd test/
test:
  script:
    - bash test_workflow_local.sh
    - bash test_dag.sh
    - bash test_rule_graph.sh
