name: mir-pipelines
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - graphviz=2.40.1
  - pip=20.0.2
  - python=3.7.4
  - singularity=3.5.2
  - snakemake==6.10.0
  - unzip=6.0
  - wget==1.20.1
