name: mirflowz
dependencies:
  - black>=24.1
  - coverage>=7.8
  - flake8>=7.2
  - flake8-docstrings>=1.7.0
  - bioconda::gffutils=0.12
  - mypy>=1.15
  - pylint>=3.3.7
  - pysam>=0.23
  - pytest>=8.3.5
  - pytest-cov>=6.1.1
  - bioconda::snakefmt>=0.11
  - bioconda::snakemake>=8
