name: mirflowz
channels:
  - conda-forge
  - bioconda
dependencies: 
  - black>=24.1.1
  - coverage>=7.3.2
  - flake8>=6.1.0
  - flake8-docstrings>=1.7.0
  - gffutils>=0.12
  - mypy>=1.6.1
  - pylint>=3.0.1
  - pysam>=0.22.0
  - pytest>=7.4.2
  - pytest-cov
  - snakefmt
  - snakemake=7.24.0
