name: mirflowz
dependencies:
  - bioconda::gffutils>=0.13
  - bioconda::snakefmt>=0.11
  - bioconda::snakemake>=8
  - black>=24.1
  - coverage>=7.8
  - flake8>=7.2
  - flake8-docstrings>=1.7.0
  - graphviz
  - mypy>=1.15
  - pulp
  - pylint>=3.3.7
  - pysam=0.23.0
  - pytest>=8.3.5
  - pytest-cov>=6.1.1
  - python>=3.12
