name: mir_pipelines
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.4
  - singularity=3.5.2
  - wget==1.20.1
  - graphviz=2.40.1
  - unzip=6.0
  - pip=20.0.2
  - pip:
    - snakemake==5.10.0
