name: mirflowz
channels:
  - conda-forge
  - bioconda
dependencies: 
  - coverage>=7.2
  - flake8 >=3.8.4
  - flake8-docstrings >=1.6.0     
  - gffutils>=0.11.1
  - mypy >=1.5
  - pylint >=2.7.1
  - pysam>=0.21.0
  - pytest>=7.1.2
  - pytest-cov
  - snakefmt
  - snakemake==7.24.0
