name: mirflowz
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - graphviz=2.40.1
  - jinja2=2.11.2
  - networkx=2.5
  - pygments=2.6.1
  - python=3.7.4
  - snakemake=6.10.0
  - unzip=6.0
  - wget==1.20.1
