---
#############################
#### REQUIRED PARAMETERS ####
#############################

samples: test_files/samples_table.csv 

#### GENOME RESOURCES ####


genome_file: test_files/Homo_sapiens.GRCh38.dna_sm.chromosome.Y.fa.gz
gtf_file: test_files/Homo_sapiens.GRCh38.98.gtf.gz 
mirna_file: test_files/hsa.gff3
map_chr_file: test_files/GRCh38_UCSC2ensembl.txt



###############################
#### "OPTIONAL" PARAMETERS ####
###############################

#### DIRECTORIES #####

output_dir: results/
local_log: logs/local/
cluster_log: logs/cluster/
scripts_dir: ../scripts/


#### ISOMIR GENERATION PARAMETERS ####

bp_5p: [-2, -1, 0, +1, +2]
bp_3p: [-2, -1, 0, +1, +2]


#### PROCESSING PARAMETERS #### 

# quality filter
q_value: 10 
p_value: 50 

# adapter removal
error_rate: 0.1    
minimum_length: 15 
overlap: 3         
max_n: 0           

# mapping
max_length_reads: 30 
nh: 100              

#### QUANTIFICATION PARAMETERS ####

mir_list: ["miRNA", "miRNA_primary_transcript"]
...