name: mirflowz
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies: 
  - coverage >=7.2
  - flake8 >=3.8.4
  - flake8-docstrings >=1.6.0
  - gffutils >=0.11.1
  - graphviz==7.1.0
  - mypy >=1.5
  - pylint >=2.7.1
  - pysam >=0.21.0
  - pytest >=7.1.2
  - pytest-cov
  - python==3.9.16
  - snakefmt
  - snakemake==7.24.0
