---
  ##############################################################################
  ### DOWNLOAD INPUT FILES:
  ### Input files: copy the local path of the files or the FTP
  ##############################################################################
  #input_files: "...."
  #output_folder: "/scicore/home/zavolan/devagy74/projects/mir-prepare-annotation/snakemake/downloaded_data"

  ##############################################################################
  ### Annotation
  ##############################################################################
  genome: "/scicore/home/zavolan/GROUP/test_datasets/annotation/Homo_sapiens.GRCh38.dna_sm.primary_assembly.clean.fa"
  transcriptome: "/scicore/home/zavolan/GROUP/test_datasets/annotation/Homo_sapiens.GRCh38.cdna.all.ncrna.clean.fa"
  gtf: "/scicore/home/zavolan/GROUP/test_datasets/annotation/Homo_sapiens.GRCh38.89.chr.gtf"
  
  ##############################################################################
  ### Directories
  ##############################################################################
  output_dir: "results"
  scripts_dir: "scripts"
  local_log: "logs/local_log"
  cluster_log: "logs/cluster_log"



...
