---
  ##############################################################################
  ### DOWNLOAD INPUT FILES:
  ##############################################################################


  ##############################################################################
  ### Files
  ##############################################################################
  genome: "/scicore/home/zavolan/devagy74/projects/filter-anno/GRCh38.genome.processed.fa"
  gtf: "/scicore/home/zavolan/devagy74/projects/filter-anno/GRCh38_96.gene_annotations.filtered.gtf"
  
  ##############################################################################
  ### Directories
  ##############################################################################
  output_dir: "results"
  scripts_dir: "scripts"
  local_log: "logs/local_log"
  cluster_log: "logs/cluster_log"
...
