name: CI

on:
  pull_request:
    branches:
     - dev
  push:
    branches:
      - '*'
 
jobs:

  snakemake-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v3
         
      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          activate-environment: mirflowz
          environment-file: environment.yml
          auto-activate-base: false
      
      - name: Update mirflowz env with root packages
        run: mamba env update -n mirflowz -f environment.root.yml
      
      - name: Update mirflowz env with dev packages
        run: mamba env update -n mirflowz -f environment.dev.yml
        
      - name: Run test for rule graph
        run: bash test/test_rule_graph.sh
      
      - name: Check workflow descriptor files for lints
        uses: snakemake/snakemake-github-action@v1
        with:
         directory: '.test'
         snakefile: 'workflow/Snakefile'
         args: '--configfile="config.yaml" --lint'
        
      - name: Run local test
        run: bash test/test_workflow_local.sh
