name: CI

on:
  pull_request:
    branches:
     - dev
  push:
    branches:
      - '*'
 
jobs:

  snakemake-test-via-singularity:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
  
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v3
         
      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          activate-environment: mirflowz
          environment-file: install/environment.root.yml
          auto-activate-base: false
        
      - name: Display environment info
        run: |
          conda info -a
          conda list

      - name: Run test for rule graph
        run: bash test/test_rule_graph.sh
      
      - name: Check workflow descriptor files for lints
        working-directory: ./test
        run: snakemake --snakefile="../workflow/Snakefile" --configfile="config.yaml" --lint
        
      - name: Run local test with Singularity
        run: bash test/test_workflow_local_with_singularity.sh


  snakemake-test-via-conda:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
  
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v3
         
      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          activate-environment: mirflowz
          environment-file: install/environment.yml
          auto-activate-base: false
      
      - name: Display environment info
        run: |
          conda info -a
          conda list

      - name: Run test for rule graph
        run: bash test/test_rule_graph.sh
      
      - name: Check workflow descriptor files for lints
        working-directory: ./test
        run: snakemake --snakefile="../workflow/Snakefile" --configfile="config.yaml" --lint
        
      - name: Run local test with Conda
        run: bash test/test_workflow_local_with_conda.sh

      
  unit-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v3
         
      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          activate-environment: mirflowz
          environment-file: install/environment.dev.yml
          auto-activate-base: false

      - name: Display environment info
        run: |
          conda info -a
          conda list

      - name: run unit tests
        working-directory: ./scripts/tests
        run: pytest --cov=scripts --cov-branch --cov-report=term-missing
