name: tests

on:
  pull_request:
    branches:
     - dev
  push:
    branches:
      - '*'
 
jobs:

  static-code-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: check out repository
        uses: actions/checkout@v4
         
      - name: Setup Conda/Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          miniforge-variant: Mambaforge
          channels: conda-forge,bioconda
          channel-priority: true
          activate-environment: mirflowz
          environment-file: install/environment.dev.yml
          auto-activate-base: false
      
      - name: display environment info
        run: |
          conda info -a
          conda list

      - name: flake8
        working-directory: ./scripts
        run: flake8 ./*.py

      - name: mypy
        working-directory: ./scripts
        run: mypy ./*.py

      - name: pylint
        working-directory: ./scripts
        run: pylint --rcfile=../pylint.cfg ./*.py


  snakemake-format-graph-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
  
    steps:
    
      - name: check out repository
        uses: actions/checkout@v4
         
      - name: setup Conda/Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          activate-environment: mirflowz
          environment-file: install/environment.dev.root.yml
          auto-activate-base: false
      
      - name: display environment info
        run: |
          conda info -a
          conda list   

      - name: run test for snakemake format
        run: bash test/test_snakefmt.sh

      - name: run test for snakemate lint
        run: bash test/test_snakemake_lint.sh 

      - name: run test for rule graph
        run: bash test/test_rule_graph.sh


  snakemake-singularity-integration-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
  
    steps:
    
      - name: check out repository
        uses: actions/checkout@v4
         
      - name: setup Conda/Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          miniforge-variant: Mambaforge
          channels: conda-forge,bioconda
          channel-priority: true
          activate-environment: mirflowz
          environment-file: install/environment.root.yml
          auto-activate-base: false
      
      - name: display environment info
        run: |
          conda info -a
          conda list   

      - name: run local test with Singularity
        run: bash test/test_workflow_local_with_singularity.sh


  snakemake-conda-integration-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
  
    steps:
    
      - name: check out repository
        uses: actions/checkout@v4
         
      - name: setup Conda/Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          miniforge-variant: Mambaforge
          channels: conda-forge,bioconda
          channel-priority: true
          activate-environment: mirflowz
          environment-file: install/environment.yml
          auto-activate-base: false
      
      - name: display environment info
        run: |
          conda info -a
          conda list   

      - name: run local test with Conda
        run: bash test/test_workflow_local_with_conda.sh


  unit-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    
      - name: checkout repository
        uses: actions/checkout@v4
         
      - name: setup Conda/Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          miniforge-variant: Mambaforge
          channels: conda-forge,bioconda
          channel-priority: true
          activate-environment: mirflowz
          environment-file: install/environment.dev.yml
          auto-activate-base: false
      
      - name: display environment info
        run: |
          conda info -a
          conda list
      
      - name: run unit tests
        working-directory: ./scripts/tests
        run: pytest --cov=scripts --cov-branch --cov-report=term-missing
